services:
  frontend:
    environment:
      - NUXT_API_BASE_URL=${NUXT_API_BASE_URL}
    build:
      context: ./fotolyrik_frontend
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./fotolyrik_backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ${WORKSPACE:?error}/uploads:/uploads
    depends_on:
      database:
        condition: service_healthy
    restart: always

  database:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      # In case you have a database dump, uncomment the following line and change the file name
      # - ./<your_dump>.sql:/docker-entrypoint-initdb.d/<your_dump>.sql
      - ${WORKSPACE:?error}/db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}" ]
      interval: 30s
      retries: 10
      start_period: 60s
    restart: always

  db_backup:
    image: postgres:17-alpine
    environment:
      - PGPASSWORD=${DB_PASSWORD}
    volumes:
      - ${BACKUPS:?error}:/backups
    entrypoint: /bin/sh
    command: -c "sleep $(( ( $(date -d '05:00' +%s) - $(date +%s) + 86400 ) % 86400 )); \
      while true; do \
      mkdir -p /backups/$(date +'%Y-%m-%d'); \
      pg_dump -h database -U ${DB_USER} ${DB_NAME} | gzip > /backups/$(date +'%Y-%m-%d')/fotolyrik_$(date +'%H%M%S').sql.gz; \
      sleep 86400; \
      done"
    depends_on:
      database:
        condition: service_healthy
    restart: always

  nginx:
    image: nginx:alpine-slim
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - "${PORT_NGINX:-80}:80"
    depends_on:
      - frontend
    restart: always
