CREATE TABLE contribution
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    internal_notes     OID,
    general_notes      OID,
    contributor_id     BIGINT,
    pseudonym          VARCHAR(255),
    photopoem_id       BIGINT                                  NOT NULL,
    role               VARCHAR(255),
    CONSTRAINT pk_contribution PRIMARY KEY (id)
);

CREATE TABLE copyright_status
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    internal_notes     OID,
    general_notes      OID,
    value              VARCHAR(255),
    description        VARCHAR(255),
    CONSTRAINT pk_copyright_status PRIMARY KEY (id)
);

CREATE TABLE file
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    internal_notes     OID,
    general_notes      OID,
    original_filename  VARCHAR(255),
    filename           VARCHAR(255),
    path               VARCHAR(255),
    type               VARCHAR(255),
    size               BIGINT,
    photopoem_id       BIGINT,
    CONSTRAINT pk_file PRIMARY KEY (id)
);

CREATE TABLE full_text
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    internal_notes     OID,
    general_notes      OID,
    photopoem_id       BIGINT                                  NOT NULL,
    full_text          TEXT,
    CONSTRAINT pk_full_text PRIMARY KEY (id)
);

CREATE TABLE keyword
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    internal_notes     OID,
    general_notes      OID,
    value              VARCHAR(255)                            NOT NULL,
    gnd_id             VARCHAR(255),
    CONSTRAINT pk_keyword PRIMARY KEY (id)
);

CREATE TABLE language
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    internal_notes     OID,
    general_notes      OID,
    name               VARCHAR(255),
    iso_designation    VARCHAR(255),
    CONSTRAINT pk_language PRIMARY KEY (id)
);

CREATE TABLE location
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    internal_notes     OID,
    general_notes      OID,
    name               VARCHAR(255),
    description        VARCHAR(255),
    CONSTRAINT pk_location PRIMARY KEY (id)
);

CREATE TABLE person
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    internal_notes     OID,
    general_notes      OID,
    first_name         VARCHAR(255),
    last_name          VARCHAR(255),
    studio_name        VARCHAR(255),
    birth_year         INTEGER,
    death_year         INTEGER,
    sex                VARCHAR(255),
    gnd_id             VARCHAR(255),
    notes              VARCHAR(255),
    file_id            BIGINT,
    CONSTRAINT pk_person PRIMARY KEY (id)
);

CREATE TABLE person_pseudonymes
(
    person_id  BIGINT NOT NULL,
    pseudonyms VARCHAR(255)
);

CREATE TABLE photopoem
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date             TIMESTAMP WITHOUT TIME ZONE,
    created_by               VARCHAR(255),
    last_modified_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by         VARCHAR(255),
    internal_notes           OID,
    general_notes            OID,
    title                    VARCHAR(255),
    subtitle                 VARCHAR(255),
    alt_title                VARCHAR(255),
    series                   VARCHAR(255),
    volume                   BIGINT,
    issue                    BIGINT,
    page_number              VARCHAR(255),
    manifest_page_number     BIGINT,
    page_count               BIGINT,
    picture_count            VARCHAR(255),
    publication_date         VARCHAR(255),
    pub_medium_id            BIGINT,
    form                     VARCHAR(255),
    link                     VARCHAR(255),
    iiif_manifest            VARCHAR(255),
    images_visible           VARCHAR(255) DEFAULT 'INTERNAL',
    copyrightstatus_image_id BIGINT,
    copyrightstatus_text_id  BIGINT,
    CONSTRAINT pk_photopoem PRIMARY KEY (id)
);

CREATE TABLE photopoem_authors
(
    person_id    BIGINT NOT NULL,
    photopoem_id BIGINT NOT NULL,
    CONSTRAINT pk_photopoem_authors PRIMARY KEY (person_id, photopoem_id)
);

CREATE TABLE photopoem_depicted_people
(
    person_id    BIGINT NOT NULL,
    photopoem_id BIGINT NOT NULL,
    CONSTRAINT pk_photopoem_depicted_people PRIMARY KEY (person_id, photopoem_id)
);

CREATE TABLE photopoem_image_motifs
(
    keyword_id   BIGINT NOT NULL,
    photopoem_id BIGINT NOT NULL,
    CONSTRAINT pk_photopoem_image_motifs PRIMARY KEY (keyword_id, photopoem_id)
);

CREATE TABLE photopoem_languages
(
    language_id  BIGINT NOT NULL,
    photopoem_id BIGINT NOT NULL,
    CONSTRAINT pk_photopoem_languages PRIMARY KEY (language_id, photopoem_id)
);

CREATE TABLE photopoem_locations
(
    location_id  BIGINT NOT NULL,
    photopoem_id BIGINT NOT NULL,
    CONSTRAINT pk_photopoem_locations PRIMARY KEY (location_id, photopoem_id)
);

CREATE TABLE photopoem_other_contributors
(
    person_id    BIGINT NOT NULL,
    photopoem_id BIGINT NOT NULL,
    CONSTRAINT pk_photopoem_other_contributors PRIMARY KEY (person_id, photopoem_id)
);

CREATE TABLE photopoem_photographers
(
    person_id    BIGINT NOT NULL,
    photopoem_id BIGINT NOT NULL,
    CONSTRAINT pk_photopoem_photographers PRIMARY KEY (person_id, photopoem_id)
);

CREATE TABLE photopoem_themes
(
    keyword_id   BIGINT NOT NULL,
    photopoem_id BIGINT NOT NULL,
    CONSTRAINT pk_photopoem_themes PRIMARY KEY (keyword_id, photopoem_id)
);

CREATE TABLE place
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    internal_notes     OID,
    general_notes      OID,
    name               VARCHAR(255)                            NOT NULL,
    description        VARCHAR(255),
    longitude          DOUBLE PRECISION                        NOT NULL,
    latitude           DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_place PRIMARY KEY (id)
);

CREATE TABLE pub_medium
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    internal_notes     OID,
    general_notes      OID,
    title              VARCHAR(255)                            NOT NULL,
    subtitle           VARCHAR(255),
    pub_medium_id      BIGINT,
    editorial_office   VARCHAR(255),
    start_year         SMALLINT,
    end_year           SMALLINT,
    amount_volumes     BIGINT,
    amount_issues      BIGINT,
    zdb_id             VARCHAR(255),
    notes              VARCHAR(255),
    CONSTRAINT pk_pub_medium PRIMARY KEY (id)
);

CREATE TABLE pub_medium_place
(
    pub_medium_id BIGINT NOT NULL,
    pub_place_id  BIGINT NOT NULL,
    CONSTRAINT pk_pub_medium_place PRIMARY KEY (pub_medium_id, pub_place_id)
);

CREATE TABLE pub_medium_rhythm
(
    pub_medium_id BIGINT NOT NULL,
    pub_rhythm_id BIGINT NOT NULL,
    CONSTRAINT pk_pub_medium_rhythm PRIMARY KEY (pub_medium_id, pub_rhythm_id)
);

CREATE TABLE publication_rhythm
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    internal_notes     OID,
    general_notes      OID,
    value              VARCHAR(255),
    description        VARCHAR(255),
    CONSTRAINT pk_publication_rhythm PRIMARY KEY (id)
);

CREATE TABLE publisher
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255),
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   VARCHAR(255),
    internal_notes     OID,
    general_notes      OID,
    name               VARCHAR(255),
    description        VARCHAR(255),
    CONSTRAINT pk_publisher PRIMARY KEY (id)
);

ALTER TABLE full_text
    ADD CONSTRAINT uc_full_text_photopoem UNIQUE (photopoem_id);

ALTER TABLE keyword
    ADD CONSTRAINT uc_keyword_value UNIQUE (value);

ALTER TABLE person
    ADD CONSTRAINT uc_person_file UNIQUE (file_id);

ALTER TABLE photopoem_themes
    ADD CONSTRAINT fk_photopoem_themes_on_photopoem FOREIGN KEY (photopoem_id) REFERENCES photopoem (id) ON DELETE CASCADE;

ALTER TABLE photopoem_image_motifs
    ADD CONSTRAINT fk_photopoem_image_motifs_on_photopoem FOREIGN KEY (photopoem_id) REFERENCES photopoem (id) ON DELETE CASCADE;

ALTER TABLE photopoem_themes
    ADD CONSTRAINT fk_photopoem_themes_on_keyword FOREIGN KEY (keyword_id) REFERENCES keyword (id);

ALTER TABLE contribution
    ADD CONSTRAINT fk_contribution_on_contributor FOREIGN KEY (contributor_id) REFERENCES person (id) ON DELETE CASCADE;

ALTER TABLE contribution
    ADD CONSTRAINT fk_contribution_on_photopoem FOREIGN KEY (photopoem_id) REFERENCES photopoem (id);

ALTER TABLE file
    ADD CONSTRAINT fk_file_on_photopoem FOREIGN KEY (photopoem_id) REFERENCES photopoem (id);

ALTER TABLE full_text
    ADD CONSTRAINT fk_full_text_on_photopoem FOREIGN KEY (photopoem_id) REFERENCES photopoem (id);

ALTER TABLE person
    ADD CONSTRAINT fk_person_on_file FOREIGN KEY (file_id) REFERENCES file (id);

ALTER TABLE photopoem
    ADD CONSTRAINT fk_photopoem_on_copyrightstatus_image FOREIGN KEY (copyrightstatus_image_id) REFERENCES copyright_status (id);

ALTER TABLE photopoem
    ADD CONSTRAINT fk_photopoem_on_copyrightstatus_text FOREIGN KEY (copyrightstatus_text_id) REFERENCES copyright_status (id);

ALTER TABLE photopoem
    ADD CONSTRAINT fk_photopoem_on_pub_medium FOREIGN KEY (pub_medium_id) REFERENCES pub_medium (id);

ALTER TABLE pub_medium
    ADD CONSTRAINT fk_pub_medium_on_publisher FOREIGN KEY (pub_medium_id) REFERENCES publisher (id);

ALTER TABLE photopoem_image_motifs
    ADD CONSTRAINT fk_photopoem_image_motifs_on_keyword FOREIGN KEY (keyword_id) REFERENCES keyword (id);

ALTER TABLE person_pseudonymes
    ADD CONSTRAINT fk_person_pseudonymes_on_person FOREIGN KEY (person_id) REFERENCES person (id);

ALTER TABLE photopoem_authors
    ADD CONSTRAINT fk_photopoem_authors_on_person FOREIGN KEY (person_id) REFERENCES person (id);

ALTER TABLE photopoem_authors
    ADD CONSTRAINT fk_photopoem_authors_on_photopoem FOREIGN KEY (photopoem_id) REFERENCES photopoem (id);

ALTER TABLE photopoem_depicted_people
    ADD CONSTRAINT fk_photopoem_depicted_people_on_person FOREIGN KEY (person_id) REFERENCES person (id);

ALTER TABLE photopoem_depicted_people
    ADD CONSTRAINT fk_photopoem_depicted_people_on_photopoem FOREIGN KEY (photopoem_id) REFERENCES photopoem (id);

ALTER TABLE photopoem_languages
    ADD CONSTRAINT fk_photopoem_languages_on_language FOREIGN KEY (language_id) REFERENCES language (id);

ALTER TABLE photopoem_languages
    ADD CONSTRAINT fk_photopoem_languages_on_photopoem FOREIGN KEY (photopoem_id) REFERENCES photopoem (id);

ALTER TABLE photopoem_locations
    ADD CONSTRAINT fk_photopoem_locations_on_location FOREIGN KEY (location_id) REFERENCES location (id);

ALTER TABLE photopoem_locations
    ADD CONSTRAINT fk_photopoem_locations_on_photopoem FOREIGN KEY (photopoem_id) REFERENCES photopoem (id);

ALTER TABLE photopoem_other_contributors
    ADD CONSTRAINT fk_photopoem_other_contributors_on_person FOREIGN KEY (person_id) REFERENCES person (id);

ALTER TABLE photopoem_other_contributors
    ADD CONSTRAINT fk_photopoem_other_contributors_on_photopoem FOREIGN KEY (photopoem_id) REFERENCES photopoem (id);

ALTER TABLE photopoem_photographers
    ADD CONSTRAINT fk_photopoem_photographers_on_person FOREIGN KEY (person_id) REFERENCES person (id);

ALTER TABLE photopoem_photographers
    ADD CONSTRAINT fk_photopoem_photographers_on_photopoem FOREIGN KEY (photopoem_id) REFERENCES photopoem (id);

ALTER TABLE pub_medium_place
    ADD CONSTRAINT fk_pub_medium_place_on_place FOREIGN KEY (pub_place_id) REFERENCES place (id);

ALTER TABLE pub_medium_place
    ADD CONSTRAINT fk_pub_medium_place_on_pub_medium FOREIGN KEY (pub_medium_id) REFERENCES pub_medium (id);

ALTER TABLE pub_medium_rhythm
    ADD CONSTRAINT fk_pub_medium_rhythm_on_pub_medium FOREIGN KEY (pub_medium_id) REFERENCES pub_medium (id);

ALTER TABLE pub_medium_rhythm
    ADD CONSTRAINT fk_pub_medium_rhythm_on_publication_rhythm FOREIGN KEY (pub_rhythm_id) REFERENCES publication_rhythm (id);
